//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace = "http://ClaimsProviderService", ConfigurationName = "IClaimsProviderService")]
public interface IClaimsProviderService
{

    [System.ServiceModel.OperationContractAttribute(Action = "http://ClaimsProviderService/IClaimsProviderService/GetSaml11Token", ReplyAction = "http://ClaimsProviderService/IClaimsProviderService/GetSaml11TokenResponse")]
    string GetSaml11Token();
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IClaimsProviderServiceChannel : IClaimsProviderService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class ClaimsProviderServiceClient : System.ServiceModel.ClientBase<IClaimsProviderService>, IClaimsProviderService
{

    public ClaimsProviderServiceClient()
    {
    }

    public ClaimsProviderServiceClient(string endpointConfigurationName) :
        base(endpointConfigurationName)
    {
    }

    public ClaimsProviderServiceClient(string endpointConfigurationName, string remoteAddress) :
        base(endpointConfigurationName, remoteAddress)
    {
    }

    public ClaimsProviderServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
        base(endpointConfigurationName, remoteAddress)
    {
    }

    public ClaimsProviderServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
        base(binding, remoteAddress)
    {
    }

    public string GetSaml11Token()
    {
        return base.Channel.GetSaml11Token();
    }
}
